services:
  - 'docker'

# Language set to shell is supposedly a minimal travis base container
# (avoid various language # support)?
language: shell

dist: bionic

env:
  - QUIET=true

script:
  - cd docker
  # Temporary hack! Print something for every 50 lines... because the log
  # length exceeds Travis maximum, but something MUST be printed otherwise
  # Travis assumes the job is dead instead :-/
  - docker build --tag buildcapicxx . | awk 'NR % 50 == 0' | while read x ; do echo "." ; done

after_success:
  - echo "PLACEHOLDER push finished docker image"
