services:
  - 'docker'

# Language set to shell is supposedly a minimal travis base container
# (avoid various language # support)?
language: shell

dist: bionic

env:
  - QUIET=true

script:
  - cd docker
  # Temporary : Avoid most of the log because it overflows the Travis maximum
  - docker build --tag buildcapicxx . | tail -1000

after_success:
  - echo "PLACEHOLDER push finished docker image"
